application: scribblevault
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /admin.*
  script: admin.app
  login: admin

- url: /.*
  script: main.app

